version: '3'

services:
  api:
    container_name: api
    build: docker/go/
    ports:
      - 3001:3001
    links:
      - mysql
    tty:
      true
    volumes:
      - ./src:/go/src

  mysql:
    container_name: mysql
    build: ./docker/mysql/
    hostname: mysql
    ports:
      - "33060:33060"
    environment: 
      TZ: Asia/Tokyo
      MYSQL_DATABASE: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake
    volumes:
      - "./docker/mysql/my.conf:/etc/mysql/my.conf"
      - "./docker/mysql/init/:/docker-entrypoint-initdb.d"
